server:
  port: 8065
spring:
  application:
    name: yi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.136.236.82:3306/enhancement_blog?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: WOAIbellayy21
    type: com.alibaba.druid.pool.DruidDataSource
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  cloud:
    alicloud:
      access-key: LTAI5tFSRXuZ3c4Gs7iNVExb
      secret-key: GMDSlkxpvqD00H3vrYmKxQ3D9a2lTm
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: yi-blog
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
logging:
    level:
      root: info
      com.yi: debug
    file:
      name: log/blog.log
comment.1: /images/comment/1.svg
comment.2: /images/comment/2.svg
comment.3: /images/comment/3.svg
comment.4: /images/comment/4.svg
comment.5: /images/comment/5.svg
comment.6: /images/comment/6.svg
comment.7: /images/comment/7.svg
comment.8: /images/comment/8.svg
comment.9: /images/comment/9.svg
comment.10: /images/comment/10.svg
comment.11: /images/comment/11.svg
comment.12: /images/comment/12.svg