server:
  port: 8065
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.136.236.82:3306/enhancement_blog?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      max-lifetime: 30000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  cloud:
    alicloud:
      access-key: LTAI5tFSRXuZ3c4Gs7iNVExb
      secret-key: GMDSlkxpvqD00H3vrYmKxQ3D9a2lTm
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: yi-blog
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
logging:
    level:
      root: info
      com.yi: debug
    file:
      name: log/blog.log
comment.1: /images/comment/1.svg
comment.2: /images/comment/2.svg
comment.3: /images/comment/3.svg
comment.4: /images/comment/4.svg
comment.5: /images/comment/5.svg
comment.6: /images/comment/6.svg
comment.7: /images/comment/7.svg
comment.8: /images/comment/8.svg
comment.9: /images/comment/9.svg
comment.10: /images/comment/10.svg
comment.11: /images/comment/11.svg
comment.12: /images/comment/12.svg